26. Remove Duplicates from Sorted Array
konstter/kbrezhnev pull request #6
Opened 2021-09-05 15:29 UTC by konstter

2021-09-05 19:41 UTC, nikitos-irk requested changes

2021-09-05 19:41 UTC, nikitos-irk commented on 26.Remove_Duplicates_from_Sorted_Array.py
> +            nums.remove(nums[i])
here you modify the array but in the description it says that you should do that **in-place**
but the `remove` operation actually modifies it, so you just break the rule :)

the correct idea is to put all the duplicates to the back of the array, and store all unique values in the begging of your array.
the idea is the same as in 27th task

2021-09-07 02:46 UTC, konstter reviewed
The new version

2021-09-07 05:54 UTC, nikitos-irk approved these changes

2021-09-08 01:29 UTC, merged